### ISSUE TITLE
make a talks page

### ISSUE THREAD

**Issue by njtierney** [rbind/njtierney.com#1]
Work out a nice way to show / present my talks from my website, either through some plugin, or some way of presenting the slides directly. 

I think @yihui uses updog to host his slides, if I remember correctly?

**Comment by njtierney** [comment]
It would be ideal to have this at talks.njtierney.com, perhaps this could also be a separate format similar to Steph Locke's awesome site: http://lockedata.uk/

**Comment by yihui** [comment]
Yes, I host all my slides in Dropbox and serve them using Updog. I was early and lucky enough to get the liftetime Updog membership for only $5.

**Comment by njtierney** [comment]
dang, $5 lifetime is pretty crazy!

I'll try it for a year and see how it goes, I think. Would just hosting the .html of my talk be OK? Or do I need to render images from the slides?

**Comment by yihui** [comment]
HTML is fine. Updog is basically a middleman server that turns your folder to a website: https://bookdown.org/yihui/blogdown/updog.html

To me, the major benefit is implicit uploading thanks to Dropbox. Other than that, you do not have to use Updog. You can explicitly upload/update your slides in a GIT repo, for example, and create a new site on Netlify to host your slides. It is free.

**Comment by njtierney** [comment]
OK that's interesting!

I tried to use updog, but my slides don't have the styling from xaringan: https://njtierney.updog.co/talks/wombat17.html#1

I just have [this html file](https://github.com/njtierney/talks/blob/master/2017/wombat/2017-06-02-tidy-miss.html) linked, not sure why it doesn't work?

Basically what I think I want is a page like [talks](http://jtleek.com/talks/) and then I want those links to point to something like `talks.njtierney.com/<talk-slug>` or `njtierney.com/talks/<talk-slug>` which would point to the full slideshow like yours: https://slides.yihui.name/2017-DSM-Journal-Yihui-Xie.html#1

Ideally I want to keep my talks in the same repository as my website.

**Comment by yihui** [comment]
I see what you meant. The HTML file itself is certainly not enough, because HTML slides generated from xaringan are not self-contained by default. All dependencies have to be shipped with the HTML file. I just render my slides in Dropbox so I don't need to worry about anything, because everything is in Dropbox, including images. It seems you rendered your slides elsewhere and only copied the HTML file to Dropbox. In that case, it is probably not worth using Updog, since it may be a hassle to copy multiple files over to Dropbox.

**Comment by njtierney** [comment]
I got it working now, now I just work on my talks in the dropbox folder and link to the html slide in the talks page - http://www.njtierney.com/talks/

**Comment by yihui** [comment]
Actually you may want to take advantage of the idea I came up with earlier this (last) week: https://bookdown.org/yihui/blogdown/static-files.html
