### ISSUE TITLE
work out how to host images

### ISSUE THREAD

**Issue by njtierney** [rbind/njtierney.com#3]
For some reason I cannot use a directory structure to point to an image.

I think that @yihui uses updog to host his images/gifs, from a dropbox folder, and then he just points to the website from those. That sounds like a good idea.

**Comment by yihui** [comment]
Correct. Usually I avoid putting images under version control because they are binary files and I want to keep the size of my repo as small as possible (the size can easily grow to several hundreds of Mb with a lot of images). Most of images on my website are hosted via Dropbox + Updog.

**Comment by njtierney** [comment]
I'm happy to pay for updog for this, it will at the worst be a fun experiment for a year. 

I'll let you know how I go!

**Comment by njtierney** [comment]
This now works, currently using updog
