### ISSUE TITLE
Hyperlink in code chunk [Question]

### ISSUE THREAD

**Issue by JauntyJJS** [rbind/njtierney.com#63]
Hi,

May I ask how did you manage to create the hyperlinks to the documentation for a given function in R ?

![image](https://user-images.githubusercontent.com/9066508/134613818-1f0340fe-dc82-4aca-8b1d-8e07e0fdfb98.png)

Was it something that hugo-xmin has or is it a css file that enables it ?

**Comment by njtierney** [comment]
Hi there!

I'm actually not 100% I remember how I did that! The hyperlinks are generated from [`downlit`](https://github.com/r-lib/downlit) - which I think is from using hugodown for my blog - so I think it happened "automagically". Sorry I wish I had a better answer!
